
# tasks file for roles/nginx

- name: Установить Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

# Открыть порт 80 для Nginx
- name: Открыть порт 80 для Nginx
  ufw:
    rule: allow
    port: 80
    proto: tcp

# Настроить конфигурацию Nginx
- name: Настроить Nginx
  copy:
    src: default
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: '0644'

# Создать папку для документов Nginx
- name: Создать папку для Nginx
  file:
    path: /var/www/html/nginx
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

# Перезапустить Nginx
- name: Перезапустить Nginx
  service:
    name: nginx
    state: restarted
